CREATE TABLE IF NOT EXISTS site_stats (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  visitors INTEGER NOT NULL DEFAULT 0,
  hits INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO site_stats(id, visitors, hits, updated_at)
VALUES (1, 0, 0, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO NOTHING;
